// ---------------------------
// This file was generated by Nango (v0.69.14)
// You can version this file
// ---------------------------

export interface SyncMetadata_asana_tasks {
};

export interface AsanaTask {
  gid: string;
  resource_type: string;
  resource_subtype: string;
  name: string;
  created_at: string | null;
  modified_at: string | null;
  start_at: string | null;
  start_on: string | null;
  due_at: string | null;
  due_on: string | null;
  completed_at: string | null;
  workspace: {  gid: string;
  resource_type: string;
  name?: string | undefined;};
  projects: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  dependencies: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  notes: string | null;
  parent: {  gid: string;
  resource_type: string;
  name?: string | undefined;} | null;
  permalink_url: string;
  id: string;
};

export interface SyncMetadata_asana_projects {
};

export interface AsanaProject {
  gid: string;
  resource_type: string;
  name: string;
  id: string;
  due_on: string | null;
  start_on: string | null;
  completed_at: string | null;
  notes: string | null;
  created_at: string;
  modified_at: string;
  permalink_url: string;
};

export interface ActionInput_asana_updateproject {
  id: string;
  notes?: string | undefined;
  due_on?: string | undefined;
};

export interface ActionOutput_asana_updateproject {
  gid: string;
  resource_type: string;
  name: string;
  id: string;
  due_on: string | null;
  start_on: string | null;
  completed_at: string | null;
  notes: string | null;
  created_at: string;
  modified_at: string;
  permalink_url: string;
};

export interface ActionInput_asana_createtask {
  name: string;
  notes?: string | undefined;
  projects: string[];
  start_on?: string | undefined;
  due_on?: string | undefined;
};

export interface ActionOutput_asana_createtask {
  gid: string;
  resource_type: string;
  resource_subtype: string;
  name: string;
  created_at: string | null;
  modified_at: string | null;
  start_at: string | null;
  start_on: string | null;
  due_at: string | null;
  due_on: string | null;
  completed_at: string | null;
  workspace: {  gid: string;
  resource_type: string;
  name?: string | undefined;};
  projects: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  dependencies: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  notes: string | null;
  parent: {  gid: string;
  resource_type: string;
  name?: string | undefined;} | null;
  permalink_url: string;
};

export interface ActionInput_asana_updatetask {
  id: string;
  due_on?: string | undefined;
  completed?: boolean | undefined;
  notes?: string | undefined;
  name?: string | undefined;
};

export interface ActionOutput_asana_updatetask {
  gid: string;
  resource_type: string;
  resource_subtype: string;
  name: string;
  created_at: string | null;
  modified_at: string | null;
  start_at: string | null;
  start_on: string | null;
  due_at: string | null;
  due_on: string | null;
  completed_at: string | null;
  workspace: {  gid: string;
  resource_type: string;
  name?: string | undefined;};
  projects: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  dependencies: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  notes: string | null;
  parent: {  gid: string;
  resource_type: string;
  name?: string | undefined;} | null;
  permalink_url: string;
};

export interface ActionInput_asana_deletetask {
  id: string;
};

export interface ActionOutput_asana_deletetask {
};

export interface ActionInput_asana_addasanadependencies {
  id: string;
  dependencies: string[];
};

export interface ActionOutput_asana_addasanadependencies {
};

export interface ActionInput_asana_removeasanadependencies {
  id: string;
  dependencies: string[];
};

export interface ActionOutput_asana_removeasanadependencies {
};

export interface RocketlaneProject {
  id: string;
  projectId: number;
  projectName: string;
  startDate?: string | null | undefined;
  dueDate?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
  owner: {  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;};
  teamMembers: {  members: ({  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;})[];
  customers: ({  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;})[];};
  customer: {  companyId: number;
  companyName: string;};
  archived: boolean;
  status: {  value: number;
  label: string;};
};

export interface RocketlaneTask {
  id: string;
  taskId: number;
  taskName: string;
  taskDescription?: string | null | undefined;
  startDate?: string | null | undefined;
  dueDate?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
  archived: boolean;
  createdBy: {  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;};
  updatedBy: {  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;};
  status: {  value: number;
  label: string;};
  project: {  projectId: number;
  projectName: string;};
  dependencies?: ({  taskId: number;
  taskName: string;})[] | undefined;
  parent?: {  taskId: number;
  taskName: string;} | undefined;
  type?: string | undefined;
};

export interface RocketlaneUser {
  id: string;
  userId: number;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email: string;
  type: 'TEAM_MEMBER' | 'CUSTOMER' | 'PARTNER' | 'EXTERNAL_PARTNER';
  status: 'ACTIVE' | 'INACTIVE' | 'INVITED' | 'PASSIVE';
  role: {  roleId: number;
  roleName: string;};
  company: {  companyId: number;
  companyName: string;};
  createdAt: string;
  updatedAt: string;
};

export interface ActionInput_rocketlane_updaterocketlaneproject {
  id: string;
  dueDate?: string | null | undefined;
};

export interface ActionOutput_rocketlane_updaterocketlaneproject {
  id: string;
  projectId: number;
  projectName: string;
  startDate?: string | null | undefined;
  dueDate?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
  owner: {  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;};
  teamMembers: {  members: ({  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;})[];
  customers: ({  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;})[];};
  customer: {  companyId: number;
  companyName: string;};
  archived: boolean;
  status: {  value: number;
  label: string;};
};

export interface ActionInput_rocketlane_updaterocketlanetask {
  id: string;
  dueDate?: string | null | undefined;
  startDate?: string | null | undefined;
  taskName?: string | undefined;
  taskDescription?: string | null | undefined;
  status?: {  value: number;} | undefined;
};

export interface ActionOutput_rocketlane_updaterocketlanetask {
  id: string;
  taskId: number;
  taskName: string;
  taskDescription?: string | null | undefined;
  startDate?: string | null | undefined;
  dueDate?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
  archived: boolean;
  createdBy: {  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;};
  updatedBy: {  emailId: string;
  userId: number;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;};
  status: {  value: number;
  label: string;};
  project: {  projectId: number;
  projectName: string;};
  dependencies?: ({  taskId: number;
  taskName: string;})[] | undefined;
  parent?: {  taskId: number;
  taskName: string;} | undefined;
  type?: string | undefined;
};

export interface ActionInput_slack_sendmessage {
  channel: string;
  text: string;
  username?: string | undefined;
  icon_url?: string | undefined;
};

export interface ActionOutput_slack_sendmessage {
  ok: boolean;
  channel?: string | undefined;
  ts?: string | undefined;
  message?: string | undefined;
  warning?: string | undefined;
  error?: string | undefined;
  raw_json: string;
};
