// ---------------------------
// This file was generated by Nango (v0.69.5)
// You can version this file
// ---------------------------

export interface SyncMetadata_asana_tasks {
};

export interface AsanaTask {
  gid: string;
  resource_type: string;
  resource_subtype: string;
  name: string;
  created_at: string | null;
  modified_at: string | null;
  start_at: string | null;
  start_on: string | null;
  due_at: string | null;
  due_on: string | null;
  completed_at: string | null;
  workspace: {  gid: string;
  resource_type: string;
  name?: string | undefined;};
  projects: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  dependencies: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  notes: string | null;
  parent: {  gid: string;
  resource_type: string;
  name?: string | undefined;} | null;
  permalink_url: string;
  id: string;
};

export interface SyncMetadata_asana_projects {
};

export interface AsanaProject {
  gid: string;
  resource_type: string;
  name: string;
  id: string;
  due_on: string | null;
  start_on: string | null;
  completed_at: string | null;
  notes: string | null;
  created_at: string;
  modified_at: string;
  permalink_url: string;
};

export interface ActionInput_asana_updateproject {
  id: string;
  notes?: string | undefined;
  due_on?: string | undefined;
};

export interface ActionOutput_asana_updateproject {
  gid: string;
  resource_type: string;
  name: string;
  id: string;
  due_on: string | null;
  start_on: string | null;
  completed_at: string | null;
  notes: string | null;
  created_at: string;
  modified_at: string;
  permalink_url: string;
};

export interface ActionInput_asana_createtask {
  name: string;
  notes?: string | undefined;
  projects: string[];
  start_on?: string | undefined;
  due_on?: string | undefined;
};

export interface ActionOutput_asana_createtask {
  gid: string;
  resource_type: string;
  resource_subtype: string;
  name: string;
  created_at: string | null;
  modified_at: string | null;
  start_at: string | null;
  start_on: string | null;
  due_at: string | null;
  due_on: string | null;
  completed_at: string | null;
  workspace: {  gid: string;
  resource_type: string;
  name?: string | undefined;};
  projects: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  dependencies: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  notes: string | null;
  parent: {  gid: string;
  resource_type: string;
  name?: string | undefined;} | null;
  permalink_url: string;
};

export interface ActionInput_asana_updatetask {
  id: string;
  due_on?: string | undefined;
  completed?: boolean | undefined;
  notes?: string | undefined;
  name?: string | undefined;
};

export interface ActionOutput_asana_updatetask {
  gid: string;
  resource_type: string;
  resource_subtype: string;
  name: string;
  created_at: string | null;
  modified_at: string | null;
  start_at: string | null;
  start_on: string | null;
  due_at: string | null;
  due_on: string | null;
  completed_at: string | null;
  workspace: {  gid: string;
  resource_type: string;
  name?: string | undefined;};
  projects: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  dependencies: ({  gid: string;
  resource_type: string;
  name?: string | undefined;})[] | null;
  notes: string | null;
  parent: {  gid: string;
  resource_type: string;
  name?: string | undefined;} | null;
  permalink_url: string;
};

export interface ActionInput_asana_deletetask {
  id: string;
};

export type ActionOutput_asana_deletetask = boolean

export interface ActionInput_slack_sendmessage {
  channel: string;
  text: string;
  username?: string | undefined;
  icon_url?: string | undefined;
};

export interface ActionOutput_slack_sendmessage {
  ok: boolean;
  channel?: string | undefined;
  ts?: string | undefined;
  message?: string | undefined;
  warning?: string | undefined;
  error?: string | undefined;
  raw_json: string;
};
